name: Continuos Integration

on:
 pull_request
    branches:
      ['master', 'main']

jobs: 
continuos-integration:
runs-on: ubuntu-latest


  steps:
  # -pegar o repositorio 
  - uses: actions/checkout@v3
  # faz um git clone do repositorio para uma branch especifica v3 é a mais atual 
  # instalar o node "npm "
  -name: Using Node.js
  uses: actions/setup-node@v2
  #passar o argumento para dentro da actions
  with:
    node-version: 20.x
  # - instalar as dependencias 
  -name: run install, build and test
  # indicar os comandos 
  run: |
    npm install
  # - executar o build
    npm run build 
    npm run test


